# Generated by Django 4.1.5 on 2023-01-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("price", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=100)),
            ],
        ),
    ]
